{{- if $.Values.argocd.enable -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocd.app.name }}
  namespace: argocd
  labels:
    app.kubernetes.io/name: {{ .Values.argocd.app.name }}
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "-" }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  project: operational
  source:
    repoURL: {{ .Values.argocd.app.repoURL }}
    targetRevision: {{ .Values.argocd.app.version }}
    path: {{ .Values.argocd.app.path }}
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
{{end -}}
